### PR TITLE
The big conflict fix merge - mess with this PR and you make Kris very sad...

### PR DESCRIPTION
**Pull request by kbjarkefur**

### CODE REVIEW

**Comment by bbdaniels** [comment]
Flagging that we need to resolve bibliography file before completing, lots of missing refs at this stage. @kbjarkefur how easy/hard is this to do in an automated way?

**Comment by bbdaniels** [comment]
Introduction also needs to be rewritten to point to correct locations in the manuscript but this is minor.

**Comment by kbjarkefur** [comment]
I have requested jabref to be installed on my computer to see if I can solve your first comment that way. And I have listed your second comment in an issue: https://github.com/worldbank/dime-data-handbook/issues/472

**Comment by bbdaniels** [comment]
@kbjarkefur Is this the appropriate time to change the filenames and chapter titles?

**Comment by bbdaniels** [comment]
@mariaruth @luizaandrade @kbjarkefur I have done a pass at incorporating 1B into 2 in e01972199ac7affb1e8b6d723517ef6848f456e6 -- please have a look. It shouldn't require too much revision on its own here. Attaching just that portion here for review.

[1B-2.pdf](https://github.com/worldbank/dime-data-handbook/files/4887562/1B-2.pdf)

**Comment by kbjarkefur** [comment]
Seems like you did not push the commit where you incorporated 1B into 2

**Comment by bbdaniels** [comment]
Haha yes, done now

**Comment by kbjarkefur** [comment]
I will merge this now. I think some material integrated at the end of ch 2 is now duplicated in other chapters. But at this point I think we should merge this. clean up file names and then do fixes like that.

**Pull request merged**
