### PR TITLE
[WIP] Link Wiki for printed resources and add DIME/i2i citations

### PR DESCRIPTION
**Pull request by bbdaniels**

### CODE REVIEW

**Comment by bbdaniels** [comment]
@Avnish95 #428

**Comment by bbdaniels** [comment]
@luizaandrade @kbjarkefur Can you review and merge this as soon as possible. In 30444b7f7ba8652d69f3be8817ebf362aed17519 we found that a lot of content had been overwritten through an odd merge-revert interaction at 05f6f97ad6e6b0f65e9ac3dfd68f8f8ad0ed580,  4e80f47ab9226f4a189b6b7b2bbb2ced3c0f6636, and 9586cd7012e6640c4a3856826e57c77143798fff. So I restored this but it led to lots of changes. Please check and flag anything that doesn't look right. It was mostly my stuff that had already been reviewed I think.

**Comment by kbjarkefur** [comment]
Very time consuming to test this exhaustively, but I sampled a few edits I did in a few different chapters and they were all there. At least we know where to look in case we find something in the future

**Comment by bbdaniels** [comment]
Thanks!

**Pull request merged**
